site_name: HPE GreenLake for File Storage Data Reduction Estimation Probe
site_description: Reference documentation for the HPE GreenLake for File Storage Data Reduction Estimation Probe
site_url: https://irisyzj.github.io/hpe-gl4f-probe
site_author: Hewlett Packard Enterprise
theme:
  name: readthedocs
  custom_dir: hpe_theme/
repo_name: 'irisyzj/hpe-gl4f-probe'
repo_url: 'https://github.com/irisyzj/hpe-gl4f-probe'
copyright: "Copyright 2023 Hewlett Packard Enterprise Development LP"
extra_css:
  - css/hpedev.css
use_directory_urls: false
markdown_extensions:
  - admonition:
  - toc:
      permalink: True
      separator: "_"
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
plugins:
  - search:
  - macros:
      include_dir: '.'
nav:
  - GET STARTED:
    - 'Prerequisites': prerequisites/index.md
    - 'Deployment': deployment/index.md
    - 'Understanding Output': output/index.md
    - 'Troubleshooting': troubleshooting/index.md
    - 'Manual Deployment': manual/index.md
    - 'FAQ': faq/index.md
  - LEGAL:
    - 'End User License Agreement': 'legal/eula/index.md'
    - 'Notices': 'legal/notices/index.md'
    - 'Support': 'legal/support/index.md'
